### PR TITLE
Rename RunningOnMono -> IsRunningOnMono

### PR DESCRIPTION
**Pull request by hishamco**
Rename to follow the [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/vstudio/ms229012(v=vs.110).aspx)

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@hishamco__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by muratg** [comment]
@Tratcher could you take this?

**Comment by Tratcher** [comment]
@hishamco  It doesn't appear to be used, you can just remove it.

**Comment by hishamco** [comment]
It was too old :smile: , I will remove it now

**Comment by hishamco** [comment]
I made the PR #9 instead

**Pull request closed without merging**
