### PR TITLE
Add travis and Nginx

### PR DESCRIPTION
**Pull request by BrennanConroy**
@Tratcher @JunTaoLuo

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
do you need to install bower and gulp before hand? like https://github.com/aspnet/Entropy/blob/dev/.travis.yml#L27-L29

**Comment by BrennanConroy** [comment]
We don't use those in ServerTests

**Comment by JunTaoLuo** [comment]
:+1: Should we also add appveyor too?

**Comment by davidfowl** [comment]
Why do we do these kinds of things in the travis.yml only?

**Comment by JunTaoLuo** [comment]
:shipit:

**Pull request merged**
